[build]
target-dir = './.build/cargo'
incremental = true
# using RUSTC_WRAPPER
rustc-wrapper = "sccache"
pipelining = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]
# rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[profile.release]
lto = "fat"  # Performs "fat" LTO which attempts to perform optimizations across all crates within the dependency graph
strip = true
